name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - access-token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
